### ISSUE TITLE
flyingWhenCantFly, breakWhenNotWorldBuilder, placeWhenNotWorldBuilder, and chatWhenMuted

### ISSUE THREAD

**Issue by Meltinglce** [DenielWorld/VanillaCommands#5]
Move all the ability stuff to a new branch until you can get it working. If you are op, you cannot:
- Fly
- Chat
- Break blocks
- Place blocks 
...
So, just move all of it to a new branch like ability-cmd or something.

**Comment by DenielWorld** [comment]
I see, since op has all permissions including the ones taking away abilities. I will fix this soon.

**Comment by DenielWorld** [comment]
It should now be fixed, please try the latest build.
